In [4]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(matrix.shape)

(3, 3)


In [6]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
